#ifndef _RPN_H_
#define _RPN_H_

// MACROS PARA AS OPERAÇÕES POSSÍVEIS E PARA SEREM EMPILHADAS NO VETOR DE DOUBLE DA PILHA

#define MULT -1 // SE O CHAR FOR "*", EMPILHA -1
#define DIV -2 // SE O CHAR FOR "/", EMPILHA -2
#define SUM -3 // SE O CHAR FOR "+", EMPILHA -3
#define SUB -4 // SE O CHAR FOR "-", EMPILHA -4

#define SUCESS 0
#define FAIL -1

// STRUCT USADA PARA EXPRESSAR A NOTAÇÃO POLONESA REVERSA
typedef struct RPN RPN_t;

struct RPN
{
	double* notacao; // VETOR COM OS NÚMEROS E AS OPERAÇOES DA EXPRESSÃO
	int tam; // TAMANHO DA NOTAÇÃO
};

int Verifica_Parenteses(char* exp); // VERIFICA SE OS PARENTESES ESTÃO CORRETOS NA EXPRESSÃO, RETORNA 0 SE CORRETO, E -1 SE DA ERRO
RPN_t* ConToRPN(char* exp); // TRANSFORMA DA NOTAÇÃO CONVENCIONAL PARA A REVERSE POLISH NOTATION(RPN)  E RETORNA UM PONTEIRO PARA STRUCT RPN_t
double resolve_notacao(RPN_t* RPN); // RESOLVE UMA EXPRESSÃO EM RPN E PRINTA O SEU RESULTADO. RETORNA FAIL, CASO HAJA ERRO OU DIVISÃO POR 0


#endif